# Build stage
FROM golang:1.25.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
    go build -o /app/focus-api ./cmd/api


# Runtime stage
FROM alpine:3.22

RUN apk add --no-cache tzdata

WORKDIR /app

COPY --from=builder /app/focus-api .

ENV PORT=8080

EXPOSE 8080

CMD ["./focus-api"]